print("\n14.Write a python program to find the index of an item of an tuple.\n ans=")
d=('hi','hello','game',1,43,6,1)
print(d)
ind=d.index('hi')
print("index of 'hi' :",ind)
ind=d.index(6)
print("index of 6 :",ind)
ind=d.index(1)
print("index of 1 :",ind)
ind=d.index('hello')
print("index of 'hello' :",ind)
